# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SmartCamera

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClassificationData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClassificationData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClassificationData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClassificationData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClassificationData
    def ClassificationList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from SmartCamera.GeneralClassification import GeneralClassification
            obj = GeneralClassification()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClassificationData
    def ClassificationListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ClassificationData
    def ClassificationListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def ClassificationDataStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddClassificationList(builder, classificationList): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(classificationList), 0)
def ClassificationDataAddClassificationList(builder, classificationList):
    """This method is deprecated. Please switch to AddClassificationList."""
    return AddClassificationList(builder, classificationList)
def StartClassificationListVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ClassificationDataStartClassificationListVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartClassificationListVector(builder, numElems)
def End(builder): return builder.EndObject()
def ClassificationDataEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)